<?php

namespace Booker\BookerBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RoomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoomRepository extends EntityRepository
{
    public function getRooms()
    {
        $qb = $this->createQueryBuilder('r')
                   ->select('r.id', 'r.number');

        return $qb->getQuery()
                  ->getArrayResult();
    }
}
