booker_booker_homepage:
    path:     /
    defaults: { _controller: BookerBookerBundle:Calendar:booker }
    
booker_booker_date:
    path:     /booker/{date}
    defaults: { _controller: BookerBookerBundle:Calendar:booker }
    
booker_booker_create:
    path:     /create/{date}/{time}/{roomId}
    defaults: { _controller: BookerBookerBundle:Calendar:create }
    
booker_booker_delete:
    path:     /delete/{orderId}/{date}
    defaults: { _controller: BookerBookerBundle:Calendar:delete }
    
booker_booker_getRooms:
    path:     /getrooms
    defaults: { _controller: BookerBookerBundle:Calendar:getRooms }
    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
